# Generated by Django 4.2.1 on 2023-06-20 11:38

import cvat.apps.engine.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0067_alter_cloudstorage_credentials_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='LabeledAudio',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('frame', models.PositiveIntegerField()),
                ('group', models.PositiveIntegerField(null=True)),
                ('source', models.CharField(choices=[('auto', 'AUTO'), ('manual', 'MANUAL')], default='manual', max_length=16, null=True)),
                ('audio_selected_segments', cvat.apps.engine.models.AudioSegmentArrayField(default=[])),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.job')),
                ('label', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.label')),
            ],
            options={
                'abstract': False,
                'default_permissions': (),
            },
        ),
        migrations.AddField(
            model_name='task',
            name='phase',
            field=models.CharField(choices=[('phase1', 'PHASE1'), ('phase2', 'PHASE2')], default=cvat.apps.engine.models.Phase['PHASE1'], max_length=10),
        ),
        migrations.CreateModel(
            name='LabeledAudioAttributeVal',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('value', cvat.apps.engine.models.SafeCharField(max_length=4096)),
                ('audio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.labeledaudio')),
                ('spec', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='engine.attributespec')),
            ],
            options={
                'abstract': False,
                'default_permissions': (),
            },
        ),
    ]
