# Generated by Django 4.2.1 on 2023-09-05 08:14

import cvat.apps.engine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0068_labeledaudio_task_phase_labeledaudioattributeval'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='task',
            name='phase',
        ),
        migrations.AddField(
            model_name='job',
            name='phase',
            field=models.CharField(choices=[('phase1a', 'PHASE1A'), ('phase1b', 'PHASE1B'), ('phase2', 'PHASE2')], default=cvat.apps.engine.models.Phase['PHASE1A'], max_length=10),
        ),
    ]
