# Generated by Django 4.2.1 on 2023-10-27 08:45

import cvat.apps.engine.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('engine', '0069_remove_task_phase_job_phase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='phase',
            field=models.CharField(choices=[('phase0', 'PHASE0'), ('phase1a', 'PHASE1A'), ('phase1b', 'PHASE1B'), ('phase2', 'PHASE2')], default=cvat.apps.engine.models.Phase['PHASE0'], max_length=10),
        ),
    ]
